### ISSUE TITLE
[-] 123456 [-] Traceback (most recent call last):   File "Brute-Forc-Twitter.py", line 101, in <module>     Twitter()

### ISSUE THREAD

**Issue by Derranfold29** [0xfff0800/Brute-Forc-Twitter-#3]
I use some of your codes for pentesting. Nice work, really.

But I've got some issues with this script.
Here's the output:
[-] 123456 [-] Traceback (most recent call last):
  File "Brute-Forc-Twitter.py", line 101, in <module>
    Twitter()
  File "Brute-Forc-Twitter.py", line 78, in Twitter
    response = b.open(url, timeout=2)
  File "/home/user/.local/lib/python3.8/site-packages/mechanize/_mechanize.py", line 257, in open
    return self._mech_open(url_or_request, data, timeout=timeout)
  File "/home/user/.local/lib/python3.8/site-packages/mechanize/_mechanize.py", line 313, in _mech_open
    raise response
mechanize._response.httperror_seek_wrapper: HTTP Error 400: Bad Request

Did I missed something? I see there is a module named "twitter". I've installed the reqs. and tried that out on different distributions, always with the same outcome.

Followed all instructions. You got an idea? Thanks 0xfff0800

**Comment by Thehope4321** [comment]
Have you solved it?

Because I got a same problem like you
Help

**Comment by Thehope4321** [comment]
@Derranfold29

**Comment by Thehope4321** [comment]
@Derranfold29

**Comment by mhsenpc** [comment]
I guess login form of twitter has been changed. I see this error

```
raise ControlNotFoundError("no control matching " + description)
mechanize._form_controls.ControlNotFoundError: no control matching name 'session[username_or_email]
```
